// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package database

// Injectors from wire.go:

func NewDatabaseDriver() Drivers {
	databasePqDriver := NewPqDriver()
	databaseDrivers := NewDrivers(databasePqDriver)
	return databaseDrivers
}
