// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/prongbang/user-service/internal/database"
	"github.com/prongbang/user-service/internal/user"
)

// Injectors from wire.go:

func CreateAPI(dbDriver database.Drivers) API {
	dataSource := user.NewDataSource(dbDriver)
	repository := user.NewRepository(dataSource)
	useCase := user.NewUseCase(repository)
	handler := user.NewHandler(useCase)
	router := user.NewRouter(handler)
	apiRouters := NewRouters(router)
	apiAPI := NewAPI(apiRouters)
	return apiAPI
}
