// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package schema

import (
	"github.com/prongbang/user-service/internal/service/database"
)

// Injectors from wire.go:

func New(dbDriver database.Drivers) Schema {
	schemaUserSchema := NewUserSchema(dbDriver)
	schemaRoleSchema := NewRoleSchema(dbDriver)
	schemaUserRoleSchema := NewUserRoleSchema(dbDriver)
	schemaRBACSchema := NewRBACSchema(dbDriver)
	schemaSchema := NewSchema(schemaUserSchema, schemaRoleSchema, schemaUserRoleSchema, schemaRBACSchema)
	return schemaSchema
}
