// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"github.com/prongbang/user-service/internal/database"
	"github.com/prongbang/user-service/internal/user"
)

// Injectors from wire.go:

func CreateGRPC(dbDriver database.Drivers) GRPC {
	dataSource := user.NewDataSource(dbDriver)
	repository := user.NewRepository(dataSource)
	useCase := user.NewUseCase(repository)
	userServer := user.NewServer(useCase)
	listener := user.NewListener(userServer)
	grpc := NewGRPC(listener)
	return grpc
}
