// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/casbin/casbin/v2"
	"github.com/prongbang/user-service/internal/service/database"
	"github.com/prongbang/user-service/internal/service/user"
)

// Injectors from wire.go:

func New(dbDriver database.Drivers, enforce *casbin.Enforcer) Service {
	dataSource := user.NewDataSource(dbDriver)
	repository := user.NewRepository(dataSource)
	useCase := user.NewUseCase(repository, enforce)
	apiHandler := user.NewHandler(useCase)
	apiRouter := user.NewRouter(apiHandler)
	serviceRouters := NewRouters(apiRouter)
	serviceAPI := NewAPI(serviceRouters)
	userServer := user.NewServer(useCase)
	grpcListener := user.NewListener(userServer)
	grpc := NewGRPC(grpcListener)
	serviceService := NewService(serviceAPI, grpc)
	return serviceService
}
